---
experiment_id: ntu60_xsub_bone_pretext

dataset:
    benchmark: xsub
    modality: bone
    name: nturgb+d
    pre_transform: true
    seed: 42
    type: basic_dataset

batch_handler:
    batch_size: 256
    type: basic_batch_handler

losses:
list:
    - name: simple_info_nce_loss
      params:
        tau: 0.07
      weight: 1
    - name: kl_loss
      params:
        anneal_by: epoch
        anneal_duration: 50
        start_weight: 0
        end_weight: 1
      weight: 1
reduction: sum

model:
    backbone:
        type: variational_moco_framework
        params:
            encoder_config:
                backbone_config: 
                    type: st_gcn_model
                    params:
                        hidden_dim: 256
                        num_class: 128
        latent_dim: 64
    K: 32768

        
n_epochs: 300
    
optimizer:
    lr: 0.002
    type: adamw
    weight_decay: 0.0001

scheduler:
    params:
        gamma: 0.1
        milestones: 250
    type: MultiStepLR

validation: true